### ISSUE TITLE
Unstaging Early Access bundle crashes gateway

### ISSUE THREAD

**Issue by gbrail** [apigee/microgateway-core#68]
If I unstage a bundle -- it pretty much doesn't matter if there are multiple bundles staged or just one -- I get a long list of messages saying that the gateway PUT deployment status, followed by a long list of the following stack trace, followed by a crash:

TypeError: Cannot read property 'logging' of undefined
    at Object.init (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/logging.js:27:34)
    at new Gateway (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-core/index.js:23:11)
    at module.exports (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-core/index.js:30:10)
    at init (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/lib/gateway.js:10:27)
    at Agent.start (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/lib/server.js:40:24)
    at startServer (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/lib/agent-config.js:24:9)
    at getConfigStart (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/lib/agent-config.js:20:3)
    at configureAndStart (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/lib/agent-config.js:15:3)
    at Object.<anonymous> (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/start-agent.js:16:1)
    at Module._compile (module.js:571:32)
/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-core/lib/logging.js:27
  const logConfig = config.system.logging;

**Comment by gbrail** [comment]
Among the messages we get before the list of stack traces are the ones below.

Also, this not only happens on an un-stage, but also if we stage a second deployment that does not conflict.

Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
(node:83172) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 43 ready listeners added. Use emitter.setMaxListeners() to increase limit
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload
Successfully PUT deployment status back to apid.
Recieved reload instruction. Proceeding to reload

**Comment by mdobson** [comment]
What version of EM do you have? 3.0.1-early-access was released today that
solved something similar to this.

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Comment by gbrail** [comment]
Let me update...

**Comment by mdobson** [comment]
Okay. Sorr,y I'll make it clear when I push a new version. Today was an exception, because if this was the same as the other bug then it was logged as a P1 so I published this afternoon to unblock folks.

**Comment by gbrail** [comment]
It's better -- now I can deploy and undeploy without a crash. But it still crashes later when I try to make an APi call. Let me try...

I have two bundles deployed, with base paths "/passthrough" and "/verifykey"

Now, I unstage the one at "/verifyapikey". EM reloads without error.
  /passthrough still works
  /verifykey returns 404 as expected

Now I re-stage the bundle that I just un-staged. EM reloads without error.
  /passthrough still works
  /verifykey crashes with the stuff below:

error verify-api-key
/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-plugins/verify-api-key/index.js:47
            if (jsonBody.type == 'ErrorResult') {
                        ^

TypeError: Cannot read property 'type' of undefined
    at Request._callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/microgateway-plugins/verify-api-key/index.js:47:25)
    at Request.self.callback (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/node_modules/request/request.js:1046:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
Removing the socket file as part of cleanup
/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:96
    var interval = respawnIntervalManager.getIntervalForNextSpawn(now);
                                          ^

TypeError: respawnIntervalManager.getIntervalForNextSpawn is not a function
    at replaceWorker (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:96:43)
    at EventEmitter.replaceAndTerminateWorker (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:120:5)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at emit (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:56:15)
    at EventEmitter.emitWorkerDisconnect (/Users/gregbrail/homebrew/lib/node_modules/edgemicro/cli/lib/reload-cluster.js:168:5)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:211:13)
    at Object.onceWrapper (events.js:293:19)

**Comment by mdobson** [comment]
Gotcha. I'll take a look at it. Thanks for the reproduction steps!

**Comment by mdobson** [comment]
https://github.com/apigee/microgateway-config/pull/20
